### ISSUE TITLE
Plot function didn't show error bar for Pre-intervention after using customized BSTS model

### ISSUE THREAD

**Issue by MengyingLi** [google/CausalImpact#34]
Hi I used a customized BSTS model for CausalImpact by using `zoo` object for response variable. however the plot function didn't show the pre-intervention error bar shown as below. Any ideas about how to fix it? Thanks! 

![image](https://user-images.githubusercontent.com/6514708/66695969-4c32ac80-ec7c-11e9-9c32-8e1362d5c739.png)

**Comment by stumakha** [comment]
Same issue here. Did not even use customized model. Just moved the code to a new computer. Same code does not produce prediction interval bars.

**Comment by alhauser** [comment]
@MengyingLi : zooming into the screenshot, it seems credible bands *are* present in the pre-period, but super narrow. So it could be an artifact of the custom BSTS model that it overfits data in the pre-period, but adds a strong random walk component which makes the credible bands very wide in the post-period. I'd play around with the model to find one that better fits the actual signal.

@stumakha : did moving the code just remove the credible band in the pre-period, or everywhere? If the latter, is this the same as https://github.com/google/CausalImpact/issues/36 which is fixed in the latest version on Github?

**Comment by stumakha** [comment]
@MengyingLi I had a problem solved in #36 . slategray2 vs SlateGray2  Thank you.
