### ISSUE TITLE
CausalImpact Simulation data

### ISSUE THREAD

**Issue by dklinenberg2020** [google/CausalImpact#56]
Hello,

Big fan of the package. I'm working on my own developments to the approach and would like to compare them to the simulation data in Brodersen et al section 3. However, this dataset isn't provided in the package. Could you make available the code to create the data or the data itself? I'd like to ensure differences in simulation results aren't caused by my coding skills or weird seed issues.

Thanks!

**Comment by kaybrodersen** [comment]
Hi Danny,

Thanks for reaching out! The simulation code wasn't ported over when we
refactored the CausalImpact interface for release, which is why it's not
included in the GitHub repo. I'd recommend setting up some fresh
simulations when testing your code or comparing it with the default version.

All the best
Kay
